source 'https://github.com/MMComponent/MMSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MMDatabaseKit_Example' do
  pod 'MMDatabaseKit', :path => '../'
#  pod 'WCDB',git: 'https://github.com/Tencent/wcdb.git' , branch: 'master'
  target 'MMDatabaseKit_Tests' do
    inherit! :search_paths

    
  end
end
